# -*- coding: utf-8 -*-
"""Streamlit-serving.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qd2xRdyd6SA8xaimUmlBDyu2FYnTpUar
"""

!pip install -q streamlit

from google.colab import drive
drive.mount('/content/gdrive')

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

!unzip ngrok-stable-linux-amd64.zip

! /content/ngrok authtoken 2ZCHAlcSiDLwNu6EFiCsN91IDFM_6G54j5EUttXhGPzkakMvJ

get_ipython().system_raw('./ngrok http 8501 &')

!curl -s http://localhost:4040/api/tunnels | python3 -c \
    'import sys, json; print("Execute the next cell and the go to the following URL: " +json.load(sys.stdin)["tunnels"][0]["public_url"])'

!streamlit run /content/gdrive/MyDrive/sum_0f_3.py

!pip3 freeze > requirements.txt

