# -*- coding: utf-8 -*-
"""Sum_3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19zN62gWy95j1LCX3gLaO3whUwztRjpZD
"""

import streamlit as st
st.header("Greatest Integer App")
st.header("This finds the largest among the 3 given numbers")
#Get Input
st.subheader('User Input Parameters')
def user_input_features():
  num1 = st.number_input("NUMBER 1")
  num2 = st.number_input("NUMBER 2")
  num3 = st.number_input("NUMBER 3")
  return (num1,num2,num3)
x,y,z = user_input_features()
max = x
if(y>max):
  max = y
if(z>max):
  max = z
st.write(x,y,z)
st.subheader('Maximum Value')
st.write(max)